[text_to_image]
model = "absolute-reality-v1-8-1"
width = 512
height = 512
steps = 20
scheduler = "euler_a"
output_format = "png"

[controlnet]
model = "absolute-reality-v1-8-1"
condition = "canny-1.1"